package xml.handler;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

import xml.statechart.Statechart;

public class XMLProcessor {
		
	public void createXmlFromYakindu(String filePath) {
		boolean done = false;
		String type="";
		String injectName=" name=";
		String region="";
		try {
			PrintWriter writer = new PrintWriter("temp.xml", "UTF-8");
			BufferedReader reader = new BufferedReader(new FileReader(filePath));
			String line;
			while ((line = reader.readLine()) != null && !done) {
				if (!line.contains("xmi:XMI")) {
					if(line.contains("</sgraph:Statechart>"))
						done = true;
					line = line.replaceAll("sgraph:", "");
					line = line.replaceAll("xmi:id", "id");
					line = line.replaceAll("xsi:type", "type");
					// Tagging the pseudo states generated by Yakindu
					
					if(line.contains("regions")){
						region= line.substring(line.indexOf("name")+6,line.indexOf(">")-1);
						region=region.trim();
					}
					
					if (line.contains("type")){
						type= line.substring(line.indexOf("type")+5);
						type=type.substring(0, type.indexOf(" "));
					
						//Choice
						if(type.contains("Choice")){
							injectName=injectName.concat(type+" ");
							line=line.substring(0, line.indexOf("incomingTransitions")-1)+injectName+line.substring(line.indexOf("incomingTransitions"));
						} else{
							// Entry
							if(type.contains("Entry")){
								//type=type.substring(0,type.indexOf("y")+1)+":"+region+ type.substring(type.indexOf("y")+1);
								injectName=injectName.concat(type+" ");
								line=line.substring(0, line.indexOf(">"))+injectName+">";
							} else{
								//FinalState
								if(type.contains("FinalState")){
									injectName=injectName.concat(type+" ");
								line=line.substring(0, line.indexOf("incomingTransitions")-1)+injectName+line.substring(line.indexOf("incomingTransitions"));
								}
							}
						}
						type="";
						injectName=" name=";
					}
					writer.println(line);
				}
			}
			reader.close();
			writer.close();
		} catch (Exception e) {
		    System.err.format("Exception occurred trying to read '%s'.", filePath);
		    e.printStackTrace();
		}
	}

	public Statechart createStatechartFromXml(String filePath) throws Exception {
		JAXBContext jaxbContext = JAXBContext.newInstance(xml.statechart.Statechart.class);  
		Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();  
		File XMLfile = new File(filePath);
		return (Statechart) jaxbUnmarshaller.unmarshal(XMLfile);
	}
	
	public void writeStatechartToXml(Statechart statechart, String filePath) throws Exception {
		File file = new File(filePath);
		JAXBContext jaxbContext2 = JAXBContext.newInstance(Statechart.class);
		Marshaller jaxbMarshaller = jaxbContext2.createMarshaller();
		jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
		jaxbMarshaller.marshal(statechart, file);
	}
}
